config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations',  sessions: "my_sessions" }

  resources :photos do
    resources :comments
  end

  root 'photos#index'

  resources :posts do
    collection do
      get 'file_upload'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/photo.rb
class Photo < ApplicationRecord
  validates :userimage, presence: true
  validates :user_id, presence: true


  has_attached_file  :userimage,
  styles: {large: "640x640>", medium: "400x400#", thumb: "150x150#" }, :use_timestamp => false
  validates_attachment_content_type :userimage, content_type: /\Aimage\/.*\z/

  belongs_to :user
   has_many :comments, dependent: :destroy
end

app/controllers/photos_controller.rb
require "google/cloud/vision"


class PhotosController < ApplicationController
  before_action :authenticate_user!
  #before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end




  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])
    gon.data = @photo.userimage.url
    forgoogle = @photo.userimage.url

    #private_key =  Google::Auth::ServiceAccountCredentials.make_creds(
        #scope: 'https://www.googleapis.com/auth/cloud-platform',
        #json_key_io: StringIO.new(ENV['VISION_KEYFILE_JSON'])
      #)


      vision = Google::Cloud::Vision.new(
              project: "redoproject-163021",
              keyfile: "config/redoproject-e87605fb29d9.json",
              )

              @image = vision.image(forgoogle)
              @labels = @image.labels
               #logs
               @logs = @image.logos
               #web
              @web = @image.web.entities
              @weburl = @image.web.pages_with_matching_images
  end





  # GET /photos/new
  def new
    @photo  = current_user.photos.build
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = current_user.photos.build(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.fetch(:photo, {}).permit(:userimage, :title)
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= simple_form_for (photo) do |f| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.input :userimage %>
    <%= f.input :title %>
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/_index.html.erb
<p id="notice"><%= notice %></p>

<h1 id='photo'>Photos</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>

      <tr>
        <td><div style="display: none;" id ='<%=photo.title%>'><%=image_tag photo.userimage.url(:medium) %>
          <%=photo.title%>
          <%= link_to 'Show', photo %></div></td>

      </tr>

    <% end %>
  </tbody>
</table>

app/views/photos/_photo.html.erb
<%= render photo.comments, photo: photo%>

<%=  form_for [photo, photo.comments.new] do |f|%>
<%=  f.text_field :content, placeholder: 'Add a comment...'%>

<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<style>
#indexbutton{
  bottom:60px;
  left: 430px;
}

@media screen and (max-width: 1000px) {
  #indexbutton {
    bottom:50px;
    left: 10px;

  }
}

</style>




<div class='overlay'>
<p id="notice"><%= notice %></p>

<div class="row">
  <% @photos.each do |photo| %>
    <div class="col s12 m6 m4">
      <div class="content-block inset  ">
          <div class="card  card-panel white lighten-2 z-depth-5">
            <h5><%= photo.user.user_name%></h5>
              <div class="card-image waves-effect waves-block waves-light ">
                <%=link_to (image_tag photo.userimage.url(:large)), photo_path(photo) %>

              </div>
              <div class="card-content white z-depth-5">
                <a id='indexbutton' class="btn-floating btn-large waves-effect waves-light z-depth-5 purple lighten-5"><i class="material-icons">add</i></a>

                <span class="card-title activator grey-text text-darken-5"><i class="material-icons right">more_vert</i></span>
                <p><a href="#"><%= photo.title %></a></p>

                 <%= render 'photo', photo: photo %>

              </div>
              <div class="card-reveal">
                <span class="card-title grey-text text-darken-4">Card Title<i class="material-icons right">close</i></span>
                <p>Here is some more information about this product that is only revealed once clicked on.</p>
              </div>


          </div>

      </div>

    </div>

  <% end %>

</div>
</div>

app/views/photos/new.html.erb
<style>
.card{
  

}



</style>

<div class='backgroundimage'>

<div class="container ">
<div class='card center'>
  <div class="container ">
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>
</div >
</div >
</div >
</div >

app/views/photos/show.html.erb
<style>

#cardpanelcontainer{
position: absolute;
bottom:25px;
left:110px;
opacity: 0.9;

}
</style>




<p id="notice"><%= notice %></p>
<div  class='container'>
  <#div class='card-panel'>
    <div  class="card  z-depth-5">
      <div class="card-image waves-effect waves-block waves-light ">
        <%=image_tag @photo.userimage.url(:medium), :id=> 'img'%><br>
      <#/div>
      <div id='cardpanelcontainer' class="container">
        <div class='card-panel'>
          <h4><%= @photo.title %></h4>
          <p><%= render 'photo', photo: @photo %></p><br>
        </div>
      </div>

</div>




<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %><br>


  Enroll
  <p id="enroll"></p>
  Enroll: (Enroll yourself in the facial recognition gallery)
<div onclick="enroll()" class="switch ">
    <label>
      Off
      <input type="checkbox">
      <span class="lever"></span>
      On
    </label>
  </div>
  <button onclick="myFunction()">delete gallery</button>
</div>




</div>

<div class='container'>
  <div class='card-panel'>
    <a id="webdescriptionbut" class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></a>
    <div id='webdescription'>
      <%  @web.map do |web| %>
      <%= simple_format web.description%>
      <hr>
      <% end %>
    </div>

    <a id="weburlbut" class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></a>
    <div id='weburl'>
      <%  @weburl.each do |weburl| %>
      <a><%= simple_format weburl.url %></a>
      <hr>
      <% end %>
    </div>
  </div>
</div>





















<script>
$( document ).ready(function() {
$("#webdescription").hide();
$("#weburl").hide();
});


$( "#webdescriptionbut" ).click(function() {
$("#webdescription").fadeToggle('slow');
});

$( "#weburlbut" ).click(function() {
$("#weburl").fadeToggle('slow');
});



url = gon.data
console.log(url)

function enroll() {
// (1) set up your callback method
  function myenrollCallback(response)
  {
  document.getElementById("enroll").innerHTML = (response.responseText);
  }



// (2) prepare your parameters
var image = url; (URL)
//(or)
//var image  = data_img; //(data_img)
  var subject_id  = 'dateapp';
  var gallery_name  = '<%= @photo.title %>'
// (3) pass your params and callback to the function
  kairos.enroll(image, subject_id, gallery_name, myenrollCallback);
}



  function myFunction() {
                  // (1) set up your callback method
                  function myremoveGalleryCallback(response)
                  {
                     alert(response.responseText);
                  }

                  // (2) prepare your parameters
                  var gallery_name_ = 'dateapp';
                  // (3) pass your params and callback to the function
                  kairos.removeGallery(gallery_name_, myremoveGalleryCallback);
  }




</script>

app/views/photos/show.js.erb
console.log(9)