config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations',  sessions: "my_sessions" }

  resources :photos do
    resources :comments
  end

  root 'photos#index'

  resources :posts do
    collection do
      get 'file_upload'
    end
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<div class="navbar-fixed">
    <nav class="white z-depth-1">
       <div class="nav-wrapper">
         <a href="#" class="brand-logo right"></a>
         <div  class="brand-logo center">
         <% if user_signed_in? %>
         <ul id="nav-mobile" class="left">
         <li><%= link_to 'Home', photos_url %></li>
           <li><%= link_to 'New Photo', new_photo_path %></li>
           <li><%= link_to 'Recognize', new_post_path %></li>
           <li><%= link_to 'History', posts_url %></li>
           <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
         <% else %>
           <li><%= link_to "Login", '#' %></li>
           <li><%= link_to "Register", '#'  %></li>
         </ul>
         </div>
       </div>
         <% end %>
     </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= include_gon %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>



  </head>
  <script>
  var kairos = new Kairos('420e451e', '9b99368985ce422ae9df7616a952bd15');
  </script>

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css">
  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/js/materialize.min.js"></script>

  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>


  <body>


    <% unless devise_controller? %>
    <%= render 'layouts/navbar' %>
    <% end %>

  <%= yield %>
  </body>


</html>